name: CI

on:
  push:
    branches:
      - citest

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build project with Maven
        working-directory: ./backend
        run: mvn clean package -Dmaven.test.skip

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod u=rw,go= ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_PUBLIC_KEYS }}" > ~/.ssh/known_hosts

      - name: Copy JAR file to Google Cloud
        run: rsync -avz backend/target/backend-0.0.1-SNAPSHOT.jar ${{ secrets.SSH_USER_NAME }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER_NAME }}/app/app.jar

      - name: Restart backend on Google Cloud
        run: ssh ${{ secrets.SSH_USER_NAME }}@${{ secrets.SSH_HOST }} docker restart chronocat-backend
